# Nome do Workflow
name: DevSecOps Pipeline

# Evento que irá acionar a pipeline
on:
  push:
    branches:
      - ci/configuracao-pipeline-aws
  pull_request:
    branches:
      - ci/configuracao-pipeline-aws

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name:  Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy in S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }} #sa-east-1
          private: true